#google clound plataform
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resouces:
    requests:
      storage: 10Gi
  storageClassName: slow